### ISSUE TITLE
Bug Infestation 

### ISSUE THREAD

**Issue by Herosofme** [MrLogano/Minecrafting#6]
Have Noticed A Huge Bug Problem, I Come Home From A Long Day Of Mining Only To Find My House Infested With Sliver Fish. I Called The Exterminator Like 5 Times And Nothing He Can Do Please Help Fix This Bug Problem.

**Comment by MrLogano** [comment]
I’ve sent in Swanky to magic them out of existence. Recommend spraying De-Mob spray once every 30 mins.
